<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/main.master" AutoEventWireup="true" CodeFile="news_release_benefit.aspx.cs" Inherits="news_release_benefit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div class="content" style="min-height: 600px; padding: 15px;">
<h3 style="text-align: center;">The Education Center to Honor Local Leaders for Their Work on Behalf of Children and Families</h3>
<p style="text-align: center;">
<i>Kids’ Best Friend Benefit and Awards Dinner will be held on November 18th </i>
</p>

<p>
(Naperville, IL) – Once again, The Education Center of Developmental Resources will honor several exceptional individuals who have dedicated their time and resources to improve the lives of children and families in this community and throughout the world.<br /><br />
Awards will be presented at the center’s annual Kids’ Best Friend Benefit and Awards Dinner on Friday, November 18, in the Lisle/Naperville Hilton Grand Ballroom.<br /><br />
The Education Center is a nationally recognized children’s organization that for more than 30 years has been helping kids succeed in school and in life. With a 97 percent success rate of graduating students who are diagnosed as learning disabled and underachievers, The Education Center offers Naperville families a place of hope and help. The annual Kids’ Best Friend benefit directly supports the many programs of The Education Center.<br /><br />
This year’s award winners are:</p>
<ul>
<li>Art and Sandy Davis – Kids’ Best Friend Award   </li>  
<li>Deb Rickert – Sid L. Port Humanitarian Award</li>
<li>Annmarie Siwik –  Community Leader Award </li>
<li>Mike Tegge - Business Partner Award</li>
<li>Robert B. Berlin - Making a Difference Award</li>
</ul>     
<p>   
 “Our award winners exemplify extraordinary commitment and dedication to children and our troops,” said Dr. Michael Litow, founder and executive director of The Education Center. “These caring people are involved in stopping child abuse and neglect, working with at-risk teens and guiding them to become good citizens, strengthening our juvenile justice system, eradicating polio worldwide, and supporting our troops locally and across the country. They all help families throughout the community. We are proud to honor them at our annual Kids’ Best Friend Awards event.”
 <br /><br />
<i><b>Kids’ Best Friend Award</b></i><br /><br />
Art and Sandy Davis are well known throughout the community and state for their generosity and dedication to helping families and children. Former owners of Davis Automotive, they have visited schools and made presentations about the work place. They have made their parking lot available to youth groups for fund-raising car washes, and they have been instrumental in helping to fund life-changing scholarships through the Rotary Club of Naperville and the House of Dreams Charity Raffle.
<br /><br />Art, with Sandy at his side, has been a strong supporter of Rotary since 1976. In 2007, he became District Governor of Rotary District 6450, which includes numerous cities in the Chicago area, and has been involved in numerous local, district, and international projects for over 35 years. 
<br /><br />Through Art’s leadership, funds have been raised for nonprofits, such as Children’s Memorial Hospital in Chicago, Loaves and Fishes, Hesed House, DuPage PADS, area schools, and Naperville parks (Rotary Hill). He has also led in fund-raising efforts for Rotary’s Polio Plus program, an international effort to eradicate polio. Most recently, Art has worked to reunite Rotary International with Easter Seals through a $250,000 Rotary pledge to provide programs and materials for Easter Seals Metropolitan Chicago’s Therapeutic School and Center for Autism Research. In 2007, he helped launch “Rotary and Easter Seals: United Again to Change the World for People with Autism,” a multi-year fund-raising campaign. Art also organized “A Taste for Rotary” and worked with the Chicago White Sox to raise funds Easter Seals’ autism center. Part of the center’s first phase, a research wing, will be named in Rotary’s honor. The $32-million facility will be built in four phases over the next few years.
Art personally co-chaired Rotary’s Oktoberfest from 1994 until 2004. The event raised over $1.5 million for various not-for-profit agencies. Since it was established in 1993, Art has served on the board of Naperville Rotary Charities, the Rotary Club of Naperville’s Foundation that has raised money through its 22 House of Dreams raffles and other fund-raisers. Naperville Rotary Charities has donated almost $2.5 million to Children’s Memorial Hospital, Polio Plus, and other important causes since its inception. 
Every step of the way, Sandy Davis has been at the side of her husband, working tirelessly and silently to ensure the success of every project and event.  An equal and gracious partner, Sandy is an unsung hero. According to Art, “Sandy is the wind beneath my wings. I could not do what I do without her help and total support for the past 47 years.”
<br /><br /> 
<i><b>Sid L. Port Humanitarian Award</b></i><br /><br />
Deb Rickert is founder and president of Operation Support Our Troops – America, formerly known as Operation Support Our Troops – Illinois. The mission of the 501(c)(3) is to support the morale and well-being of troops serving in harm’s way, their families, and returning veterans.
<br /><br />Rickert has inspired our community to come together to meet the needs of troops overseas and their families here at home. Bill and Deb’s three sons – Dan, Dave, and Joe – grew up in Naperville and attended Naperville Central High School. Dan, a 2006 graduate of the United States Military Academy at West Point, has completed one tour of Iraq and is now stationed at Ft. Bragg, North Carolina. David is a newly commissioned infantry 2nd lieutenant stationed at Ft. Benning, Georgia.
<br /><br />Rickert started the organization in 2003 when her oldest son went to West Point. Since then, Operation Support Our Troops – America has grown into one of the largest volunteer-based military support organizations in the country. During the past eight years, it has raised millions of dollars and supported programs for troops, veterans, and their families. Rickert personally created a lasting partnership with actor Gary Sinise and began “Rockin’ for the Troops ™,” an annual day of support/concert for military families and supporters. With the money raised through this and other events, Operation Support Our Troops – America has raised awareness of the needs of veterans and has contributed to Hines VA Hospital, Fisher House for Illinois, the Wounded Warriors Project, the USO, and many other veteran programs.
<br /><br />Operation Support Our Troops – America has also developed a variety of programs to help troops and their families, including
</p><ul>
<li>The group sends comfort packages to deployed military members in harm’s way and special requests to units and hospitals in the field. The organization has shipped more than 35,000 cartons to troops overseas.</li>
<li>Operation Support Our Troops - America also encourages people to write letters to service men and women and provides information about opportunities for veterans.</li>
<li>Its “We Have Not Forgotten” program offers ongoing group and immediate grieving support for family members of the military.</li>
<li>Its Family Resource and Support Team provides outreach to pregnant wives of deployed service members. </li>
</ul><p>
In partnership with the United States Army Golden Knights, the organization offers a “Gold for Gold” program to provide a growth experience based on the principles of a "Leap of Faith" for families of fallen service members.  The seminar encourages families to explore the other side of grief and sadness and includes a tandem skydive with the Golden Knights.
<br /><br />One of the primary goals of the organization is to participate significantly in the national dialog regarding issues affecting our troops. Operation Support Our Troops – America advocates for new and better treatments for post traumatic stress in returning troops and veterans.
<br /><br />Rickert has served as a mentor and advisor for many Iraq and Afghanistan veterans working to create veteran support opportunities and has been actively involved with the development of programs under Operation Iraqi Freedom and Operation Enduring Freedom veteran leadership.  
<br /><br />Rickert has used her unrelenting energy, positive outlook, and psychology background to reach out to the troops, their families, members of the community, and to those who have lost family members through war.
<br /><br />Each year, this award is presented by the Lawson Products Company in honor of its founder and well-known Chicago philanthropist, Sid L. Port. Mr. Port’s legacy of giving includes generous support that helped establish The Education Center. The Education Center also offers scholarships to the families of veterans who need counseling or academic support.
 <br /><br />
<b><i>Community Leader Award </i></b>
 <br /><br />The lives of many children have been improved through the tireless work of Annmarie Siwik, the winner of the Community Leader Award. As a longtime member of the Exchange Club of Naperville, Siwik has been the sponsorship director for Ribfest for the past 10 years, raising hundreds of thousands of dollars to help protect children. One year, she was the chair of Ribfest. She is also a past president of the Exchange Club and served as district president for the Lincolnland District Exchange Clubs. As a member of the Exchange Club, she worked with Edward Hospital to set up a clinic to obtain evidence to use in criminal cases involving sexual abuse of children.
 <br /><br />Siwik is also involved in numerous community organizations. She serves as a Naperville Riverwalk Commissioner and is on the board of directors of the Naperville Parks Foundation. She is past chair of the board of directors of the Naperville Area Chamber of Commerce and is a member of several other area chambers. As a breast cancer survivor, Siwik volunteers with the American Cancer Society, Reach for Recovery Program, assisting breast cancer patients.
 <br /><br />Others in the community have recognized Siwik for her service and her achievements. She has received the Jaycees Distinguished Service Award, the Business Ledger’s 2007 Influential Women in Business Award, and the Susan B. Komen Award, Honorable Supporter of Breast Cancer Awareness. She is a two-time recipient of the Exchangite of the Year Award.
 <br /><br />Annmarie Siwik has demonstrated a high level of service that directly impacts the lives of children and young people. She exhibits extraordinary leadership, inspiring others to do more for their community.
 
<b><i>Business Partner Award</i></b> <br /><br />
When Mike Tegge became general manager of Mercedes Benz of Naperville almost two years ago, one of his goals was to establish ways the car dealership could give back to the community. Through his leadership, the company started the Naperville Community Care Program and carefully selected three local charities – NCO, The Education Center, and Loaves and Fishes – to support through regular fund-raisers. Redirecting part of the advertising budget, the dealership hosts frequent, week-long, charity test-drive events and donates $50 per test drive to the local charities. To date, Mercedes Benz of Naperville has given approximately $28,000 to local not-for-profit groups. Tegge has also dedicated a wall in the dealership’s waiting room to feature the logo of the Naperville Community Care Program and letters from local nonprofits. The staff is very supportive of the company’s efforts, and everyone is knowledgeable about the charities the dealership supports.
 <br /><br />According to Mike Tegge, “One of our goals is to create awareness about these charities. We have a lot of foot traffic in the store, and many of our visitors are business people. We hope this inspires the idea that their business could do something to help the community, too.” He added, “Naperville is a huge town, but it is really a small community. There are a lot of people in Naperville who give back. If you make people aware of things, that’s all it takes. It’s pretty cool!”
  <br /><br />
Making a Difference Award
 <br /><br />DuPage County State’s Attorney Robert Berlin, is the recipient of this year’s Making a Difference Award. In a letter nominating Berlin for this award, Dr. Darlene Ruscitti, regional superintendent of DuPage County Schools, wrote, “He has worked extensively with the Illinois and DuPage Juvenile Justice Commission and recognizes that some of the most important work that needs to happen is to ensure that all children become productive citizens of this great nation.” Ruscitti added, “Though a tough prosecutor, Bob has great compassion and respect for all people. I believe he is a great role model for our youth.” She explained that he has spoken to students in the county schools’ Alternative Opportunity Programs on many occasions. “While many students are at first intimidated and sometimes disrespectful of Mr. Berlin, Bob has a way of bringing these students around as he fascinates them with stories of heroism and everyday people doing extraordinary things. Mr. Berlin always stands up for doing what is right against all odds, standing up for the little guy, and being on the side of the toughest kids and making them just a bit softer, wiser, and more productive citizens.”
 <br /><br />Berlin has partnered extensively with the DuPage Regional Office of Education on numerous child-centered projects. He created guidelines on conducting investigations regarding youth and reporting policies related to child abuse and neglect. He and his staff also worked with the regional office of education staff on an anti-bullying initiative and a model truancy policy that speaks for children. 
 <br /><br />Berlin’s 24-year public service career began in 1987 when he became an assistant state’s attorney in the Cook County State’s Attorney Office and was later promoted to deputy supervisor of appeals. In 2001, he was appointed first assistant state’s attorney for Kane County.  According to Justice Joseph Birkett, “During his career in both Cook and Kane counties, Bob devoted himself to assisting at-risk youth. While an assistant in Cook County, Bob worked closely with law enforcement and child-abuse centers to develop comprehensive strategies to assist children who had been exploited and to bring offenders to justice.” As first assistant state’s attorney in Kane County, Berlin managed the juvenile division, working closely with the court, DCFS, CASA, and local law enforcement to address the needs of all children who receive services within the juvenile justice system. 
 <br /><br />In 2004, Birkett hired Berlin as deputy chief of the Juvenile Division of the DuPage County State’s Attorney’s Office. Berlin served as chairman of DuPage County’s Juvenile Justice Council. “During Bob’s tenure, a number of vitally important community-based interagency partnerships have been formed, including the anti-bullying task force, mandatory reporting seminars, anti-truancy policy and procedures, improved juvenile/felony screening practices, and peer jury programs,” explained Birkett.
 <br /><br />His commitment to reaching children during their formative years has truly made a difference in the lives of many young people.
 
  <br /><br />
<b><i>Ticket Information:</i></b>
 <br /><br />
Members of the community are invited to join The Education Center in honoring award winners. Tickets to the Kids’ Best Friend Award Dinner are $125 per person and include a lavish cocktail reception, dinner and dancing.  The reception begins at 5:30 p.m.
 <br /><br />For more information about The Education Center or to purchase tickets, please contact the center at 630-420-7807 or visit www.TheEducationCenter.org.  The Education Center is located at 113 East Van Buren in Naperville.


</p>
</div>
</asp:Content>

